# Site settings
title: Welcome to Eikos Technical Services LLC
# author: Michael Smith
#  name: Michael Smith
# email: your-email@domain.com
description: "Personal, bespoke IT services for small businesses and individuals since 1997"

# Build settings
remote_theme: pages-themes/modernist@v0.2.0
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
