# Site settings
title: Welcome to Eikos Technical Services LLC
author:
  name: Michael Smith
  # email: your-email@domain.com
description: "A simple page of what I do"

# Build settings
remote_theme: pages-themes/minima
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
